### ISSUE TITLE
Use private repository

### ISSUE THREAD

**Issue by AnthonyFerre** [acm-ndsu/CollabCompetition#15]
we need to keep the details of the competition private from others members of the organization

**Comment by jghibiki** [comment]
Do we really need to do this? Any game code stuff we can keep in a separate private repo, sure. But does this one need to be private? Just curious.

**Comment by AnthonyFerre** [comment]
Yes, I meant the selection of game itself and the modification made later on

**Comment by jghibiki** [comment]
Ok yeah, when we get around to that I can create a private repo under my account. We haven't applied for non-profit status with github yet :smile:

**Comment by jghibiki** [comment]
Is there anything you wanted to add or can we close this issue?

**Comment by AnthonyFerre** [comment]
Yes, it's fine
